trigger:
- main

pool:
  name: agent ka jund
steps:

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'samar_serviceconnection'
    backendAzureRmStorageAccountName: 'ranvirsingh123'
    backendAzureRmContainerName: 'amarendra'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'samar_serviceconnection'